name: efiXplorer CI
on:
  push:
  pull_request:
jobs:
  build_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Dowload IDA SDK
        shell: cmd
        env:
          IDA_SDK: ${{ secrets.DOWNLOAD_LINK_IDA_SDK }}
          PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: |
          cd ..
          curl -J -L "%IDA_SDK%" -o idasdk83.zip
          unzip -P "%PASSWORD%" idasdk83.zip
      - name: Build efiXplorer
        run: |
          mkdir build
          cd build
          cmake .. -DIdaSdk_ROOT_DIR="../../idasdk83" -DHexRaysSdk_ROOT_DIR="../../hexrays_sdk"
          cmake --build . --config Release
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer.dll
          path: build/efiXplorer/efiXplorer.dll
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer64.dll
          path: build/efiXplorer/efiXplorer64.dll
      - uses: actions/upload-artifact@master
        with:
          name: efiXloader64.dll
          path: build/efiXloader/efiXloader64.dll
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Dowload IDA SDK
        shell: bash
        env:
          IDA_SDK: ${{ secrets.DOWNLOAD_LINK_IDA_SDK }}
          PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: |
          cd ..
          curl -J -L "$IDA_SDK" -o idasdk83.zip
          unzip -P $PASSWORD idasdk83.zip
      - name: Build efiXplorer
        run: |
          mkdir build
          cd build
          cmake .. -DIdaSdk_ROOT_DIR="../../idasdk83" -DHexRaysSdk_ROOT_DIR="../../hexrays_sdk"
          cmake --build . --config Release
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer.so
          path: build/efiXplorer/efiXplorer.so
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer64.so
          path: build/efiXplorer/efiXplorer64.so
      - uses: actions/upload-artifact@master
        with:
          name: efiXloader64.so
          path: build/efiXloader/efiXloader64.so
  build_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Dowload IDA SDK
        shell: bash
        env:
          IDA_SDK: ${{ secrets.DOWNLOAD_LINK_IDA_SDK }}
          PASSWORD: ${{ secrets.ZIP_PASSWORD }}
        run: |
          cd ..
          curl -J -L "$IDA_SDK" -o idasdk83.zip
          unzip -P $PASSWORD idasdk83.zip
      - name: Build efiXplorer
        run: |
          mkdir build
          cd build
          cmake .. -DIdaSdk_ROOT_DIR="../../idasdk83" -DHexRaysSdk_ROOT_DIR="../../hexrays_sdk"
          cmake --build . --config Release
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer.dylib
          path: build/efiXplorer/efiXplorer.dylib
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer64.dylib
          path: build/efiXplorer/efiXplorer64.dylib
      - uses: actions/upload-artifact@master
        with:
          name: efiXloader64.dylib
          path: build/efiXloader/efiXloader64.dylib
