name: Build for Windows
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Dowload IDA SDK
        shell: cmd
        env:
          IDA_SDK75: ${{ secrets.DOWNLOAD_LINK_IDA_SDK }}
        run: |
          cd ..
          powershell "Invoke-WebRequest '%IDA_SDK75%' -OutFile ida_sdk_v75.zip"
          powershell "Expand-Archive -Force ida_sdk_v75.zip ida_sdk_v75"
      - name: Build efiXplorer
        run: |
          mkdir build
          cd build
          cmake .. -DIdaSdk_ROOT_DIR="..\ida_sdk_v75\idasdk75"
          cmake --build . --config Release
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer
          path: build/Release/efiXplorer.dll
      - uses: actions/upload-artifact@master
        with:
          name: efiXplorer64
          path: build/Release/efiXplorer64.dll
